name: consumiblestore-ordenes
services:
  database:
    image: postgres:latest
    container_name: ordenes_database
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./init-db:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    container_name: ordenes_backend
    restart: unless-stopped
    ports:
      - "${BACK_PORT}:3000"
    env_file:
      - .env
    depends_on:
      - database

  frontend:
    build: ./frontend
    container_name: ordenes_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
